# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tt.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from urllib.parse import urlencode
import requests
import time
import re
import json
import sys
import os
def show_MINN():
    app=QtWidgets.QApplication(sys.argv)
    M=QtWidgets.QMainWindow()
    ui=Ui_bilim()
    ui.setupUi(M)
    M.show()
    sys.exit(app.exec_())
li=0
# Q2登录方法
def qr():
    h={'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0'}
    r=requests.get('https://passport.bilibili.com/x/passport-login/web/qrcode/generate',headers=h)
    print(r.text)
    f=r.text
    f=re.search(r'({.*})',f).group(0)
    j=json.loads(f)
    curli = str(j['data']["url"])
    ll=str(j['data']['qrcode_key'])
    vep={'qrcode_key':ll}
    l ={'url':curli}
    curll= urlencode(l)
    jpgg=requests.get('https://api.pwmqr.com/qrcode/create/',params=curll)
    f=open('ddd.jpg','wb+')
    f.write(jpgg.content)
    f.close()
    os.startfile('ddd.jpg')
    print(j['data']["url"])


    while True:
        sq=requests.get('https://passport.bilibili.com/x/passport-login/web/qrcode/poll',params=vep,headers=h)
        sqq=re.search(r'({.*})',sq.text).group(0)
        sqqj=json.loads(sqq)
        if sqqj['data']['code']==0:
            print('完成')
            return sq.cookies
        else :
            print(sqqj['data']['code'])
            time.sleep(2.5)

class Ui_bilim(object):
    def setupUi(self, bilim):
        bilim.setObjectName("bilim")
        bilim.resize(1133, 757)
        self.centralwidget = QtWidgets.QWidget(bilim)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1010, 10, 111, 41))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 40, 1111, 661))
        self.tabWidget.setObjectName("tabWidget")
        self.hg = QtWidgets.QWidget()
        self.hg.setEnabled(True)
        self.hg.setObjectName("hg")
        self.widget = QtWidgets.QWidget(self.hg)
        self.widget.setGeometry(QtCore.QRect(0, -180, 1121, 801))
        self.widget.setObjectName("widget")
        self.tabWidget.addTab(self.hg, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        bilim.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(bilim)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1133, 23))
        self.menubar.setObjectName("menubar")
        bilim.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(bilim)
        self.statusbar.setObjectName("statusbar")
        bilim.setStatusBar(self.statusbar)

        self.retranslateUi(bilim)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton.clicked.connect(self.lon) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(bilim)
    def lon(self):
        global li
        if li==0:
            gh = qr()
            print(gh)

        else:
            pass

    def retranslateUi(self, bilim):
        _translate = QtCore.QCoreApplication.translate
        bilim.setWindowTitle(_translate("bilim", "MainWindow"))
        self.pushButton.setText(_translate("bilim", "登录"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.hg), _translate("bilim", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("bilim", "Tab 2"))
if __name__ == "__main__":
    show_MINN()